# Generated by Django 3.0.7 on 2020-06-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
