# Generated by Django 3.0.7 on 2020-06-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
