# Generated by Django 3.0.7 on 2020-06-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200609_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='customer_mod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer_model'),
        ),
        migrations.AddField(
            model_name='order_model',
            name='products_mod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product_model'),
        ),
    ]
