# Generated by Django 3.0.7 on 2020-07-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_model',
            name='profie_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
