# Generated by Django 3.0.7 on 2020-07-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_model_profie_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_model',
            old_name='profie_pic',
            new_name='profile_pic',
        ),
    ]
